### ISSUE TITLE
`genesis init` does not embed GEESE

### ISSUE THREAD

**Issue by Proplex** [starkandwayne/genesis#316] opened 2018-12-18 20:06 UTC
I believe this is slightly related to #294. When Genesis creates a new `*-deployments` folder, it embeds the Genesis script itself and not GEESE, which results in:

```
Can't locate Genesis.pm in @INC (you may need to install the Genesis module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./.genesis/bin/genesis line 23.
BEGIN failed--compilation aborted at ./.genesis/bin/genesis line 23.
```

When `*-deployments/.genesis/bin/genesis` is called. A hotfix for this is to call `genesis embed` in the deployments folder, which will overwrite the `.genesis/bin/genesis` file with GEESE.

This affects pipelined deployment folders that have not had `genesis embed` called on them prior.

**Comment by dennisjbell** [comment] 2018-12-19 23:02
This is a duplicate of #308

**Closed** 2018-12-20 00:56 UTC
